site_name: STEM教育理论与实践 课程补充材料

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb  
        name: Switch to dark mode
      primary: teal
    # Palette toggle for dark mode
    - scheme: slate
      primary: brown
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.annotate

nav: 
  - index.md
  - 拓展书目导读: 
    - 拓展书目导读/index.md
    - 拓展书目导读/mindstorm.md
    - 拓展书目导读/HPS.md
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
