site_name: JumpIntoDSA

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.instant
    - navigation.indexes

nav: 
  - 环境搭建: Environment/index.md
  - C++快速入门: 
    - C++/index.md
    - 类和对象: C++/Class&Object.md
    - 构造析构: C++/Cons&Dest.md
    - 继承: C++/Inheritance.md
    - 多态: C++/Polymorphism.md
    - 运算符重载: C++/Overloading.md
    - 模板简介: C++/Templates.md
    - 内存分配: C++/Memory.md
    - 引用: C++/Reference.md
  - LAB0: LAB0/index.md
  - 数学基础: Math/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
